# Generated by Django 5.1.2 on 2024-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='c_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_name',
            field=models.CharField(default='sathish', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='place',
            field=models.CharField(default='coimbatore', max_length=100),
            preserve_default=False,
        ),
    ]
