# Generated by Django 5.1.2 on 2024-10-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet_c_number_pet_owner_name_pet_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='type',
            new_name='pet_type',
        ),
    ]
