# Generated by Django 5.1.2 on 2024-10-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_petsitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitter',
            old_name='End_data',
            new_name='End_date',
        ),
        migrations.RenameField(
            model_name='petsitter',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
