# Generated by Django 5.1.2 on 2024-10-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_end_data_petsitter_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitter',
            old_name='End_date',
            new_name='end_date',
        ),
    ]
